[package]
name = "grammar-fuzzer"
version = "0.1.0"
authors = ["enchanted-engineering <dev@enchanted.engineering>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.1"
rand = "0.7.3"